---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  provisioner: kubernetes.io/azure-file
  parameters:
    type: gp2
  reclaimPolicy: Retain
  allowVolumeExpansion: true
  mountOptions:
    - debugvolumeBindingMode: Immediate
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: harbor
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.goharbor.io'
    chart: harbor
    targetRevision: 1.9.5
    helm:
      parameters:
        - name: externalURL
          value: "https://core.20-90-125-146.nip.io"
        - name: expose.ingress.hosts.core
          value: core.20-90-125-146.nip.io
        - name: expose.ingress.hosts.notary
          value: notary.20-90-125-146.nip.io
        - name: trace.jaeger.endpoint
          value: "http://20-90-125-146.nip.io:14268/api/traces"
        - name: trace.otel.endpoint
          value: "20-90-125-146.nip.io:4318"
        - name: expose.ingress.harbor.annotations.kubernetes\.io/ingress\.class
          value: nginx
        - name: expose.ingress.notary.annotations.kubernetes\.io/ingress\.class
          value: nginx
        - name: expose.tls.secret.secretName
          value: tlsname
        - name: expose.tls.secret.notarySecretName
          value: notarytlsname
        - name: expose.tls.certSource
          value: secret
        - name: expose.ingress.harbor.annotations.cert-manager\.io/cluster-issuer
          value: letsencrypt-prod
        - name: expose.ingress.notary.annotations.cert-manager\.io/cluster-issuer
          value: letsencrypt-prod
        - name: chartmuseum.enabled
          value: "false"
        - name: persistence.persistentVolumeClaim.registry.accessMode
          value: ReadWriteMany
        - name: persistence.persistentVolumeClaim.registry.size
          value: 50Gi
        # - name: persistence.persistentVolumeClaim.chartmuseum.accessMode
        #   value: ReadWriteMany
        # - name: persistence.persistentVolumeClaim.chartmuseum.size
        #   value: 5Gi
        - name: persistence.persistentVolumeClaim.jobservice.accessMode
          value: ReadWriteMany
        - name: persistence.persistentVolumeClaim.database.size
          value: 5Gi
        - name: persistence.persistentVolumeClaim.registry.storageClass
          value: standard
        # - name: persistence.persistentVolumeClaim.chartmuseum.storageClass
        #   value: standard
        - name: persistence.persistentVolumeClaim.jobservice.storageClass
          value: standard
        - name: portal.replicas
          value: 2
        - name: core.replicas
          value: 2
        - name: jobservice.replicas
          value: 2
        - name: registry.replicas
          value: 2
        # - name: chartmuseum.replicas
        #   value: 2
        - name: clair.replicas
          value: 2
        - name: notary.server.replicas
          value: 2
        - name: notary.signer.replicas
          value: 2
  project: harbor
  syncPolicy:
    automated:
      selfHeal: true
